/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_MIXNET_RUST__
#define __RUST_MIXNET_RUST__
#ifdef __cplusplus
extern "C" {
#endif

/** <No documentation available> */
typedef struct E2Easy E2Easy_t;


#include <stdbool.h>

/** <No documentation available> */
typedef struct JsonResult {
    /** <No documentation available> */
    bool success;

    /** <No documentation available> */
    char * data;
} JsonResult_t;

/** <No documentation available> */
JsonResult_t
e2easy_cast (
    E2Easy_t * * handle);

/** <No documentation available> */
JsonResult_t
e2easy_challenge (
    E2Easy_t * * handle);

/** <No documentation available> */
void
e2easy_free (
    E2Easy_t * it);

/** <No documentation available> */
E2Easy_t *
e2easy_new (void);

/** <No documentation available> */
JsonResult_t
e2easy_tally (
    E2Easy_t * * handle);

/** <No documentation available> */
JsonResult_t
e2easy_vote (
    E2Easy_t * * handle,
    char const * votes_json);

/** <No documentation available> */
void
json_result_free (
    JsonResult_t result);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_MIXNET_RUST__ */
